def pullClaimsNeedingNoAdditionalProcessing():
    '''
    All line_counters have only one version and one row per the version. They also have one paid date.
    This is the vast majority if the 'kspadmn' payor codes.
    We will simply take the claims as they currently exist.
    '''
    query = f'''
        drop table if exists research_dev.pi_kspadmn_base_claims_kspadmn;
        with claims as (
            select payor_code, trim(payor_claim_control_number) as pccn, trim(carrier_specific_unique_member_id) as mem_id
            from research_dev.pi_payor_specific_claims_kspadmn
            where date_of_service_from::int / 10000 >= 2019 and payor_code in (20000040)
            group by 1,2,3
            having count(distinct paid_date) = 1 and count(distinct version_number) = 1
        )
        insert into research_dev.pi_final_claims_kspadmn
        select distinct
            c.apcd_id::bigint,
            a.data_submitter_code,
            a.payor_code,
            trim(carrier_specific_unique_member_id) mem_id,
            trim(carrier_specific_unique_subscriber_id) sub_id,
            pccn,
            line_counter,
            trim(member_zip_code),
            to_date(date_of_service_from::text, 'YYYMMDD'),
            to_date(date_of_service_thru::text, 'YYYMMDD'),
            to_date(paid_date::text, 'YYYMMDD'),
            to_date(admission_date::text, 'YYYMMDD'),
            admission_hour,
            admission_type,
            point_of_origin,
            to_date(discharge_date::text, 'YYYMMDD'),
            discharge_hour,
            discharge_status,
            trim(type_of_bill_institutional) bill,
            trim(place_of_service_professional) place_of_service,
            trim(revenue_code),
            trim(procedure_code),
            trim(procedure_modifier_1),
            trim(procedure_modifier_2),
            trim(procedure_modifier_3),
            trim(procedure_modifier_4),
            trim(admitting_diagnosis),
            first_external_cause_code,
            icd_version_indicator,
            trim(principal_diagnosis),
            trim(other_diagnosis_1),
            trim(other_diagnosis_2),
            trim(other_diagnosis_3),
            trim(other_diagnosis_4),
            trim(other_diagnosis_5),
            trim(other_diagnosis_6),
            trim(other_diagnosis_7),
            trim(other_diagnosis_8),
            trim(other_diagnosis_9),
            trim(other_diagnosis_10),
            trim(other_diagnosis_11),
            trim(other_diagnosis_12),
            trim(other_diagnosis_13),
            trim(other_diagnosis_14),
            trim(other_diagnosis_15),
            trim(other_diagnosis_16),
            trim(other_diagnosis_17),
            trim(other_diagnosis_18),
            trim(other_diagnosis_19),
            trim(other_diagnosis_20),
            trim(other_diagnosis_21),
            trim(other_diagnosis_22),
            trim(other_diagnosis_23),
            trim(other_diagnosis_24),
            trim(present_on_admission_code_1),
            trim(present_on_admission_code_2),
            trim(present_on_admission_code_3),
            trim(present_on_admission_code_4),
            trim(present_on_admission_code_5),
            trim(present_on_admission_code_6),
            trim(present_on_admission_code_7),
            trim(present_on_admission_code_8),
            trim(present_on_admission_code_9),
            trim(present_on_admission_code_10),
            trim(present_on_admission_code_11),
            trim(present_on_admission_code_12),
            trim(present_on_admission_code_13),
            trim(present_on_admission_code_14),
            trim(present_on_admission_code_15),
            trim(present_on_admission_code_16),
            trim(present_on_admission_code_17),
            trim(present_on_admission_code_18),
            trim(present_on_admission_code_19),
            trim(present_on_admission_code_20),
            trim(present_on_admission_code_21),
            trim(present_on_admission_code_22),
            trim(present_on_admission_code_23),
            trim(present_on_admission_code_24),
            trim(present_on_admission_code_25),
            trim(icd_cm_pcs_principal_procedure_code),
            trim(icd_cm_pcs_other_procedure_code_1),
            trim(icd_cm_pcs_other_procedure_code_2),
            trim(icd_cm_pcs_other_procedure_code_3),
            trim(icd_cm_pcs_other_procedure_code_4),
            trim(icd_cm_pcs_other_procedure_code_5),
            trim(icd_cm_pcs_other_procedure_code_6),
            trim(icd_cm_pcs_other_procedure_code_7),
            trim(icd_cm_pcs_other_procedure_code_8),
            trim(icd_cm_pcs_other_procedure_code_9),
            trim(icd_cm_pcs_other_procedure_code_10),
            trim(icd_cm_pcs_other_procedure_code_11),
            trim(icd_cm_pcs_other_procedure_code_12),
            trim(icd_cm_pcs_other_procedure_code_13),
            trim(icd_cm_pcs_other_procedure_code_14),
            trim(icd_cm_pcs_other_procedure_code_15),
            trim(icd_cm_pcs_other_procedure_code_16),
            trim(icd_cm_pcs_other_procedure_code_17),
            trim(icd_cm_pcs_other_procedure_code_18),
            trim(icd_cm_pcs_other_procedure_code_19),
            trim(icd_cm_pcs_other_procedure_code_20),
            trim(icd_cm_pcs_other_procedure_code_21),
            trim(icd_cm_pcs_other_procedure_code_22),
            trim(icd_cm_pcs_other_procedure_code_23),
            trim(icd_cm_pcs_other_procedure_code_24),
            trim(icd_cm_pcs_other_procedure_code_25),
            service_units_quantity,
            unit_of_measure,
            charge_amount,
            withhold_amount,
            plan_paid_amount,
            co_pay_amount,
            coinsurance_amount,
            deductible_amount,
            other_insurance_paid_amount,
            cob_tpl_amount,
            allowed_amount,
            payment_arrangement_type_flag,
            drug_code,
            rendering_provider_id,
            rendering_provider_npi,
            rendering_provider_entity_type_qualifier,
            in_plan_network_indicator,
            rendering_provider_first_name,
            rendering_provider_middle_name,
            rendering_provider_last_name_or_organization_name,
            rendering_provider_suffix,
            rendering_provider_specialty,
            rendering_provider_city_name,
            rendering_provider_state_or_province,
            rendering_provider_zip_code,
            rendering_provider_group_practice_npi,
            billing_provider_id,
            billing_provider_npi,
            billing_provider_last_name_or_organization_name,
            billing_providertax_id,
            referring_provider_id,
            referring_provider_npi,
            attending_provider_id,
            attending_provider_npi,
            carrier_associated_with_claim,
            type_of_claim,
            claim_status,
            denied_claim_line_indicator,
            claim_adjustment_reason_code,
            claim_line_type,
            1
        from research_dev.pi_payor_specific_claims_kspadmn a
        join claims b on a.payor_code = b.payor_code and trim(a.payor_claim_control_number) = b.pccn and trim(carrier_specific_unique_member_id) = b.mem_id
        left join research_data.xz_mpi_crosswalk c on a.payor_code = c.payor_code
        and trim(a.carrier_specific_unique_member_id::text) = c.mem_id::text;
    '''
    with connection.cursor() as cursor:
        try:
            cursor.execute(query)
            print(f"Inserted {cursor.rowcount} rows")
            cursor.execute('vacuum analyze research_dev.pi_final_claims_kspadmn;')
        except psycopg2.Error as e:
            print(f"Database error: {e}")
            raise
