import React, { useState, useEffect, useRef, useMemo, useCallback } from "react";

export const fileTypeMap = {
  js: { language: "Javascript", icon: "javascript.svg", category: "code" },
  jsx: { language: "Javascript", icon: "javascript.svg", category: "code" },
  ts: { language: "Typescript", icon: "typescript.svg", category: "code" },
  tsx: { language: "Typescript", icon: "typescript.svg", category: "code" },
  html: { language: "HTML", icon: "html.svg", category: "code" },
  css: { language: "CSS", icon: "css.svg", category: "code" },
  json: { language: "JSON", icon: "json.svg", category: "code" },
  xml: { language: "XML", icon: "xml.svg", category: "code" },
  py: { language: "Python", icon: "python.svg", category: "code" },
  php: { language: "PHP", icon: "php.svg", category: "code" },
  swift: { language: "Swift", icon: "swift.svg", category: "code" },
  c: { language: "C", icon: "c.svg", category: "code" },
  cpp: { language: "C++", icon: "c++.svg", category: "code" },
  h: { language: "C++", icon: "c++.svg", category: "code" },
  cs: { language: "C#", icon: "csharp.svg", category: "code" },
  rs: { language: "Rust", icon: "rust.svg", category: "code" },
  bash: { language: "Bash", icon: "bash.svg", category: "code" },
  sh: { language: "Shell", icon: "shell.svg", category: "code" },
  zsh: { language: "Shell", icon: "shell.svg", category: "code" },
  mc: { language: "Monkey C", icon: "monkeyc.svg", category: "code" },
  mcgen: { language: "Monkey C", icon: "monkeyc.svg", category: "code" },
  sql: { language: "SQL", icon: "sql.svg", category: "code" },
  asm: { language: "Assembly", icon: "assembly.svg", category: "code" },
  md: { language: "Markdown", icon: "markdown.svg", category: "text" },
  txt: { language: "Plain Text", icon: "txtExtension.svg", category: "text" },
  csv: { language: "CSV", icon: "csvExtension.svg", category: "tabular" },
  png: { language: null, icon: "imageExtension.svg", category: "image" },
  jpg: { language: null, icon: "imageExtension.svg", category: "image" },
  jpeg: { language: null, icon: "imageExtension.svg", category: "image" },
  gif: { language: null, icon: "videoExtension.svg", category: "image" },
  svg: { language: null, icon: "imageExtension.svg", category: "image" },
  bmp: { language: null, icon: "imageExtension.svg", category: "image" },
  mp4: { language: null, icon: "videoExtension.svg", category: "video" },
  mkv: { language: null, icon: "videoExtension.svg", category: "video" },
  avi: { language: null, icon: "videoExtension.svg", category: "video" },
  mov: { language: null, icon: "videoExtension.svg", category: "video" },
  webm: { language: null, icon: "videoExtension.svg", category: "video" },
  mp3: { language: null, icon: "audioExtension.svg", category: "audio" },
  wav: { language: null, icon: "audioExtension.svg", category: "audio" },
  flac: { language: null, icon: "audioExtension.svg", category: "audio" },
  pdf: { language: null, icon: "pdfExtension.svg", category: "pdf" },
  doc: { language: null, icon: "wordExtension.svg", category: "other" },
  docx: { language: null, icon: "wordExtension.svg", category: "other" },
  xls: { language: null, icon: "excelExtension.svg", category: "other" },
  xlsx: { language: null, icon: "excelExtension.svg", category: "other" },
  ppt: { language: null, icon: "powerpointExtension.svg", category: "other" },
  pptx: { language: null, icon: "powerpointExtension.svg", category: "other" },
  zip: { language: null, icon: "archiveExtensions.svg", category: "other" },
  rar: { language: null, icon: "archiveExtensions.svg", category: "other" },
  tar: { language: null, icon: "archiveExtensions.svg", category: "other" },
  gz: { language: null, icon: "archiveExtensions.svg", category: "other" },
  pem: { language: null, icon: "securityExtensions.svg", category: "other" },
  cache: { language: null, icon: "cacheExtensions.svg", category: "other" },
  tmp: { language: null, icon: "cacheExtensions.svg", category: "other" },
  temp: { language: null, icon: "cacheExtensions.svg", category: "other" },
  bak: { language: null, icon: "cacheExtensions.svg", category: "other" },
  dockerfile: { language: "Dockerfile", icon: "dockerfileExtension.svg", category: "code" },
  makefile: { language: "Makefile", icon: "makefileExtension.svg", category: "code" },
  git: { language: null, icon: "githubExtension.svg", category: "other" },
  stl: { language: "3D Model", icon: "threedimExtension.svg", category: "threeD" },
  "3mf": { language: "3D Model", icon: "threedimExtension.svg", category: "threeD" },
  obj: { language: "3D Model", icon: "threedimExtension.svg", category: "threeD" },
  ply: { language: "3D Model", icon: "threedimExtension.svg", category: "threeD" },
  glb: { language: "3D Model", icon: "threedimExtension.svg", category: "threeD" },
  gltf: { language: "3D Model", icon: "threedimExtension.svg", category: "threeD" },
  dae: { language: "3D Model", icon: "threedimExtension.svg", category: "threeD" },
  x3d: { language: "3D Model", icon: "threedimExtension.svg", category: "threeD" },
  off: { language: "3D Model", icon: "threedimExtension.svg", category: "threeD" }
};